import type { InvoiceLineItem } from "@/lib/invoices";

export type ServiceCategory = {
  id: string;
  slug: string;
  name: string;
  description: string;
  group: string;
  supportsInvoices: boolean;
  supportsQuotes: boolean;
  invoicePrefix: string;
  quotePrefix: string;
  defaultLineItems: InvoiceLineItem[];
  suggestedFields: string[];
  tips: string[];
};

export const serviceCategories: ServiceCategory[] = [
  {
    id: "automotive-mechanic",
    slug: "automotive-mechanic",
    name: "Automotive Mechanic",
    description: "Diagnostics, repairs, parts, shop labor, and maintenance.",
    group: "Mechanic",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "AUTO",
    quotePrefix: "QAUTO",
    defaultLineItems: [{ description: "Automotive diagnostic and labor", quantity: 1, price: 150 }],
    suggestedFields: ["Vehicle", "VIN", "Mileage", "Repair Order"],
    tips: ["List parts separately from labor.", "Use notes for exclusions and approval terms."],
  },
  {
    id: "airline-mechanic",
    slug: "airline-mechanic",
    name: "Airline Mechanic",
    description: "Aviation maintenance, inspections, parts, and mechanic labor.",
    group: "Mechanic",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "AIR",
    quotePrefix: "QAIR",
    defaultLineItems: [{ description: "Aircraft inspection and labor", quantity: 1, price: 350 }],
    suggestedFields: ["Aircraft", "Tail Number", "Inspection Type", "Work Order"],
    tips: ["Document inspection scope clearly.", "Separate approved parts from estimated labor."],
  },
  {
    id: "powersports-mechanic",
    slug: "power-sports-mechanic",
    name: "Power Sports Mechanic",
    description: "ATV, UTV, motorcycle, jet ski, and small engine service.",
    group: "Mechanic",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "PSM",
    quotePrefix: "QPSM",
    defaultLineItems: [{ description: "Power sports diagnostic and labor", quantity: 1, price: 125 }],
    suggestedFields: ["Unit", "VIN or Serial", "Mileage or Hours", "Repair Order"],
    tips: ["Include make, model, and hours when available.", "Call out parts availability in the notes."],
  },
  {
    id: "construction",
    slug: "construction",
    name: "Construction",
    description: "Project labor, materials, phases, deposits, and add-ons.",
    group: "Building",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "CONST",
    quotePrefix: "QCONST",
    defaultLineItems: [{ description: "Labor", quantity: 1, price: 500 }],
    suggestedFields: ["Project Type", "Job Location", "Start Date", "Completion Date"],
    tips: ["Break large projects into phases.", "Call out deposits, materials, and exclusions."],
  },
  {
    id: "handyman",
    slug: "handyman",
    name: "Handyman",
    description: "Repairs, installs, maintenance tasks, and small project work.",
    group: "Home Services",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "HANDY",
    quotePrefix: "QHANDY",
    defaultLineItems: [{ description: "General Handyman Labor", quantity: 1, price: 125 }],
    suggestedFields: ["Service Category", "Job Location", "Estimated Hours", "Completion Date"],
    tips: ["Group small tasks by room or trade.", "Use notes for customer-supplied materials."],
  },
  {
    id: "cleaning",
    slug: "cleaning",
    name: "Cleaning",
    description: "Residential and commercial cleaning jobs, supplies, and add-ons.",
    group: "Cleaning",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "CLEAN",
    quotePrefix: "QCLEAN",
    defaultLineItems: [{ description: "Standard Cleaning Service", quantity: 1, price: 150 }],
    suggestedFields: ["Property Type", "Square Footage", "Cleaning Frequency", "Access Notes"],
    tips: ["Separate recurring service from one-time deep cleaning.", "List supply fees as their own line item."],
  },
  {
    id: "powerwashing",
    slug: "powerwashing",
    name: "Power Washing",
    description: "Exterior cleaning for concrete, siding, patios, decks, and fences.",
    group: "Exterior Services",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "WASH",
    quotePrefix: "QWASH",
    defaultLineItems: [{ description: "Power Washing Service", quantity: 1, price: 200 }],
    suggestedFields: ["Surface Type", "Square Footage", "Water Access", "Treatment Needed"],
    tips: ["Call out pre-treatment or stain removal separately.", "Use quantity for surface area or sections."],
  },
  {
    id: "gutter-cleaning",
    slug: "gutter-cleaning",
    name: "Gutter Cleaning",
    description: "Gutter cleaning, downspout clearing, minor repairs, and add-ons.",
    group: "Exterior Services",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "GUTTER",
    quotePrefix: "QGUTTER",
    defaultLineItems: [{ description: "Gutter Cleaning Service", quantity: 1, price: 150 }],
    suggestedFields: ["Stories", "Linear Feet", "Downspouts", "Debris Level"],
    tips: ["List repairs separately from cleaning.", "Use notes for access or roof pitch concerns."],
  },
  {
    id: "lawn-care",
    slug: "lawn-care",
    name: "Lawn Care",
    description: "Mowing, edging, trimming, cleanup, and recurring yard services.",
    group: "Outdoor Services",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "LAWN",
    quotePrefix: "QLAWN",
    defaultLineItems: [{ description: "Lawn Care Service", quantity: 1, price: 85 }],
    suggestedFields: ["Lot Size", "Service Frequency", "Gate Access", "Cleanup Needed"],
    tips: ["Use recurring frequency in the project title.", "Add cleanup or haul-away as separate items."],
  },
  {
    id: "car-detailing",
    slug: "car-detailing",
    name: "Car Detailing",
    description: "Interior, exterior, full detail, wash packages, and add-ons.",
    group: "Automotive",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "DETAIL",
    quotePrefix: "QDETAIL",
    defaultLineItems: [{ description: "Full Detail Package", quantity: 1, price: 200 }],
    suggestedFields: ["Vehicle", "Package", "Condition", "Add-ons"],
    tips: ["Separate interior and exterior packages.", "Use notes for pet hair, stains, or odor treatment."],
  },
  {
    id: "towing",
    slug: "towing",
    name: "Towing",
    description: "Tows, roadside service, mileage, hook-up fees, and after-hours calls.",
    group: "Roadside Services",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "TOW",
    quotePrefix: "QTOW",
    defaultLineItems: [
      { description: "Service Call", quantity: 1, price: 75 },
      { description: "Hook-Up Fee", quantity: 1, price: 85 },
      { description: "Mileage", quantity: 1, price: 4 },
      { description: "After-Hours Fee", quantity: 1, price: 50 },
    ],
    suggestedFields: ["Vehicle", "Pickup Location", "Drop-off Location", "Tow Type"],
    tips: ["Use mileage quantity for billable miles.", "Call out after-hours or specialty equipment fees."],
  },
  {
    id: "hvac",
    slug: "hvac",
    name: "HVAC",
    description: "Heating, cooling, diagnostics, maintenance, parts, and labor.",
    group: "Home Services",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "HVAC",
    quotePrefix: "QHVAC",
    defaultLineItems: [
      { description: "Diagnostic Fee", quantity: 1, price: 95 },
      { description: "Labor", quantity: 1, price: 150 },
      { description: "Parts", quantity: 1, price: 0 },
      { description: "System Maintenance", quantity: 1, price: 125 },
    ],
    suggestedFields: ["System Type", "Brand or Model", "Issue Reported", "Service Date"],
    tips: ["Separate diagnostics from repair labor.", "Use notes for warranty or maintenance recommendations."],
  },
  {
    id: "plumbing",
    slug: "plumbing",
    name: "Plumbing",
    description: "Service calls, labor, parts, drain cleaning, and fixture work.",
    group: "Home Services",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "PLUMB",
    quotePrefix: "QPLUMB",
    defaultLineItems: [
      { description: "Service Call", quantity: 1, price: 95 },
      { description: "Labor", quantity: 1, price: 150 },
      { description: "Parts", quantity: 1, price: 0 },
      { description: "Drain Cleaning", quantity: 1, price: 175 },
    ],
    suggestedFields: ["Fixture or System", "Issue Reported", "Access Notes", "Emergency Service"],
    tips: ["List parts and labor separately.", "Use notes for access issues or follow-up recommendations."],
  },
  {
    id: "junk-removal",
    slug: "junk-removal",
    name: "Junk Removal",
    description: "Load size, labor, disposal fees, heavy items, and cleanouts.",
    group: "Hauling",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "JUNK",
    quotePrefix: "QJUNK",
    defaultLineItems: [
      { description: "Load Size", quantity: 1, price: 150 },
      { description: "Labor", quantity: 1, price: 75 },
      { description: "Disposal Fee", quantity: 1, price: 50 },
      { description: "Heavy Item Fee", quantity: 1, price: 40 },
    ],
    suggestedFields: ["Load Size", "Item Types", "Stairs or Access", "Disposal Notes"],
    tips: ["Use load size as the main pricing line.", "Call out heavy items and disposal fees separately."],
  },
  {
    id: "roofing",
    slug: "roofing",
    name: "Roofing",
    description: "Inspections, repairs, materials, labor, and roofing project work.",
    group: "Building",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "ROOF",
    quotePrefix: "QROOF",
    defaultLineItems: [
      { description: "Inspection", quantity: 1, price: 125 },
      { description: "Labor", quantity: 1, price: 500 },
      { description: "Materials", quantity: 1, price: 0 },
      { description: "Repair", quantity: 1, price: 250 },
    ],
    suggestedFields: ["Roof Type", "Damage Area", "Material", "Warranty Notes"],
    tips: ["Separate inspection, repair, and materials.", "Use notes for exclusions, weather, or warranty details."],
  },
  {
    id: "electrician",
    slug: "electrician",
    name: "Electrician Work",
    description: "Service calls, labor, materials, panel, outlet, and fixture work.",
    group: "Home Services",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "ELEC",
    quotePrefix: "QELEC",
    defaultLineItems: [
      { description: "Service Call", quantity: 1, price: 95 },
      { description: "Labor", quantity: 1, price: 150 },
      { description: "Materials", quantity: 1, price: 0 },
      { description: "Panel/Outlet/Fixture Work", quantity: 1, price: 250 },
    ],
    suggestedFields: ["Work Type", "Panel or Circuit", "Fixture Count", "Permit Needed"],
    tips: ["Use separate lines for labor and materials.", "Document permit or panel notes clearly."],
  },
  {
    id: "landscaping-maintenance",
    slug: "landscaping-maintenance",
    name: "Landscaping and Maintenance",
    description: "Lawn maintenance, mulch, beds, trimming, cleanup, and outdoor upkeep.",
    group: "Outdoor Services",
    supportsInvoices: true,
    supportsQuotes: true,
    invoicePrefix: "LAND",
    quotePrefix: "QLAND",
    defaultLineItems: [
      { description: "Lawn Maintenance", quantity: 1, price: 95 },
      { description: "Mulch/Bed Work", quantity: 1, price: 250 },
      { description: "Trimming", quantity: 1, price: 125 },
      { description: "Cleanup", quantity: 1, price: 150 },
    ],
    suggestedFields: ["Property Size", "Service Frequency", "Bed or Planting Areas", "Cleanup Scope"],
    tips: ["Separate maintenance from project work.", "Use notes for recurring schedule and cleanup scope."],
  },
];

export function getInvoiceServiceCategories() {
  return serviceCategories.filter((category) => category.supportsInvoices);
}

export function getQuoteServiceCategories() {
  return serviceCategories.filter((category) => category.supportsQuotes);
}

export function getServiceCategory(slug: string) {
  return serviceCategories.find((category) => category.slug === slug);
}
